source /home/ananthu/.zplug/init.zsh

# Plugins
# Supports oh-my-zsh plugins and the like
zplug "plugins/git",   from:oh-my-zsh
zplug "plugins/z",   from:oh-my-zsh

# Make sure to use double quotes
zplug "zsh-users/zsh-syntax-highlighting"
zplug "zsh-users/zsh-autosuggestions"

# Load theme file
zplug 'themes/agnoster', as:theme, from:oh-my-zsh

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

# Then, source plugins and add commands to $PATH
zplug load 

zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
setopt auto_cd

if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
        source /etc/profile.d/vte.sh
fi


export EDITOR='nvim'
export VISUAL='nvim'


# alias ls='ls --color=auto --group-directories-first'
# alias la='ls -A --group-directories-first'
# alias ll='ls -lAh --group-directories-first'
alias ls='exa --group-directories-first'
alias la='exa -a --group-directories-first'
alias ll='exa -alb --group-directories-first'
alias tree='exa -T'
alias bm='bashmount'
alias rg='ranger'
# alias pst='patch -o config.h -i '
# alias v='vim '
# alias gv='gvim '
alias nv='nvim '
alias gc='google-chrome-stable '
alias fx='firefox-developer-edition '
alias sclip="xclip -selection c"
alias gclip="xclip -selection c -o"
alias speedtest="curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python - "
alias grep='grep --colour=auto'
# alias egrep='egrep --colour=auto'
# alias fgrep='fgrep --colour=auto'
alias nb='newsboat '
alias irc='irssi '
alias pc='pacman '
alias pc-m='pacman-mirrors '
alias sudo='sudo '
alias watch='watch '


weather() {
    curl wttr.in/${1:-kothamangalam}
}

set -o vi

#Key bindings
bindkey "^A" beginning-of-line
bindkey "^E" end-of-line
#bindkey "^F" forward-word
#bindkey "^B" backward-word
bindkey "^L" clear-screen
bindkey "^U" backward-kill-line
#bindkey "^U" kill-whole-line
bindkey "^Y" yank
#bindkey "^W" backward-kill-word
#bindkey "^X^B" vi-match-bracket
#bindkey "^X^F" vi-find-next-char
bindkey '^R' history-incremental-search-backward
bindkey '^[[3~' delete-char-or-list

# ext - archive extractor
# usage: ext <file>
ext ()
{
  if [ -f $1 ] ; then
    case $1 in
      *.tar.bz2)   tar xjf $1   ;;
      *.tar.gz)    tar xzf $1   ;;
      *.bz2)       bunzip2 $1   ;;
      *.rar)       unrar x $1     ;;
      *.gz)        gunzip $1    ;;
      *.tar)       tar xf $1    ;;
      *.tbz2)      tar xjf $1   ;;
      *.tgz)       tar xzf $1   ;;
      *.zip)       unzip $1     ;;
      *.Z)         uncompress $1;;
      *.7z)        7z x $1      ;;
      *.iso)	   if [ $# -ne 2 ]
      		   then
		   	echo "specify the destination directory"
		   else
		   	7z x -o$2 $1
		   fi
		   ;;
      *)           echo "'$1' cannot be extracted via ext()" ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}

# Your dotdrop git repository location
export DOTREPO="~/dotfiles"

alias dotdrop="$DOTREPO/dotdrop.sh"
alias dotgit="git -C $DOTREPO"
alias dotsync="dotgit pull && dotgit add -A && dotgit commit && dotgit push; dotdrop install"

