config:
  backup: true
  create: true
  dotpath: dotfiles
  instignore:
  - '*/README.md'
  upignore:
  - '*/README.md'
dotfiles:
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_xinitrc:
    src: xinitrc
    dst: ~/.xinitrc
  d_irssi:
    src: irssi
    dst: ~/.irssi
  d_fonts:
    src: local/share/fonts
    dst: ~/.local/share/fonts
  d_xdman:
    src: xdman
    dst: ~/.xdman
    instignore:
    - '*/temp'
    - '*/metadata'
    - '*/downloads.txt'
    - '*/queues.txt'
    upignore:
    - '*/temp'
    - '*/metadata'
    - '*/downloads.txt'
    - '*/queues.txt'
  d_modified:
    src: Pictures/.wallpaper/modified
    dst: ~/Pictures/.wallpaper/modified
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  d_breeze-red:
    src: icons/Breeze-Red
    dst: ~/.icons/Breeze-Red
  d_mpv:
    src: config/mpv
    dst: ~/.config/mpv
  d_htop:
    src: config/htop
    dst: ~/.config/htop
  d_newsboat:
    src: config/newsboat
    dst: ~/.config/newsboat
  d_ranger:
    src: config/ranger
    dst: ~/.config/ranger
    instignore:
    - '*/__pycache__'
    upignore:
    - '*/__pycache__'
  d_tilix:
    src: config/tilix
    dst: ~/.config/tilix
  d_vimiv:
    src: config/vimiv
    dst: ~/.config/vimiv
  d_wallpapers_modified:
    src: Pictures/Wallpapers/modified
    dst: ~/Pictures/Wallpapers/modified
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
    instignore:
    - '*/plugged'
    - '*/.git'
    upignore:
    - '*/plugged'
    - '*/.git'
  f_plug.vim:
    src: local/share/nvim/site/autoload/plug.vim
    dst: ~/.local/share/nvim/site/autoload/plug.vim
  d_sxiv:
    src: config/sxiv
    dst: ~/.config/sxiv
  f_pacman.conf:
    src: etc/pacman.conf
    dst: /etc/pacman.conf
  f_update-resolv-conf:
    src: etc/openvpn/update-resolv-conf
    dst: /etc/openvpn/update-resolv-conf
  f_aliasrc:
    src: config/.aliasrc
    dst: ~/.config/.aliasrc
  d_scripts:
    src: config/scripts
    dst: ~/.config/scripts
  f_dconf.bak:
    src: config/dconf.BAK
    dst: ~/.config/dconf.BAK
  f_config_xmodmap:
    src: config/Xmodmap
    dst: ~/.config/Xmodmap
  f_config_xprofile:
    src: config/Xprofile
    dst: ~/.config/Xprofile
  f_xresources:
    src: config/Xresources
    dst: ~/.config/Xresources
profiles:
  manjaro:
    dotfiles:
    - f_zshrc
    - f_bashrc
    - f_xinitrc
    - d_irssi
    - d_fonts
    - d_xdman
    - d_modified
    - f_gitconfig
    - d_breeze-red
    - d_mpv
    - d_htop
    - d_newsboat
    - d_ranger
    - d_tilix
    - d_vimiv
    - d_wallpapers_modified
    - d_nvim
    - f_plug.vim
    - d_sxiv
    - f_pacman.conf
    - f_update-resolv-conf
    - f_aliasrc
    - d_scripts
    - f_dconf.bak
    - f_config_xmodmap
    - f_config_xprofile
    - f_xresources
