config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_xprofile:
    src: xprofile
    dst: ~/.xprofile
  f_xinitrc:
    src: xinitrc
    dst: ~/.xinitrc
  d_irssi:
    src: irssi
    dst: ~/.irssi
  d_fonts:
    src: local/share/fonts
    dst: ~/.local/share/fonts
  d_xdman:
    src: xdman
    dst: ~/.xdman
  f_init.zsh:
    src: zplug/init.zsh
    dst: ~/.zplug/init.zsh
  d_scripts:
    src: scripts
    dst: ~/.scripts
  d_modified:
    src: Pictures/.wallpaper/modified
    dst: ~/Pictures/.wallpaper/modified
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  d_breeze-red:
    src: icons/Breeze-Red
    dst: ~/.icons/Breeze-Red
profiles:
  manjaro:
    dotfiles:
    - f_zshrc
    - f_bashrc
    - f_xprofile
    - f_xinitrc
    - d_irssi
    - d_fonts
    - d_xdman
    - f_init.zsh
    - d_scripts
    - d_modified
    - f_gitconfig
    - d_breeze-red
